<?php session_start(); ?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Wapi Book Library</title>
    <link rel="stylesheet"
          href="<?php echo WEB_ROOT ?>/extend_libraries/bootstrap-3.3.7-dist/css/bootstrap.css"/>
    <link rel="stylesheet" href="<?php echo WEB_ROOT ?>/extend_libraries/bootstrap-3.3.7-dist/css/bootstrap-theme.min.css"/>
   <link rel="stylesheet" href="<?php echo WEB_ROOT ?>/extend_libraries/bootstrap-3.3.7-dist/css/bootstrapValidator.min.css"/>
    <link rel="stylesheet" href="<?php echo WEB_ROOT ?>/extend_libraries/bootstrap-3.3.7-dist/css/bootstrap-datetimepicker.css"/>
    <script src="<?php echo WEB_ROOT ?>/extend_libraries/bootstrap-3.3.7-dist/js/jquery-2.2.4.js"></script>
    <script src="<?php echo WEB_ROOT ?>/extend_libraries/bootstrap-3.3.7-dist/js/moment.min.js"></script>
    <script src="<?php echo WEB_ROOT ?>/extend_libraries/bootstrap-3.3.7-dist/js/bootstrap.js"></script>
    <script src="<?php echo WEB_ROOT ?>/extend_libraries/bootstrap-3.3.7-dist/js/bootstrapvalidator.min.js"></script>
    <script src="<?php echo WEB_ROOT ?>/extend_libraries/bootstrap-3.3.7-dist/js/jquery.dataTables.min.js"></script>
    <script src="<?php echo WEB_ROOT ?>/extend_libraries/bootstrap-3.3.7-dist/js/bootstrap-datetimepicker.min.js"></script>    
</head>
<body>
   

